language: node_js
node_js: --lts


before_script:
  - git config user.name "luckzp"
  - git config user.email "245527922@qq.com"
  - sed -i'' "s~https://github.com/luckzp/luckzp.github.io.git~https://${GH_TOKEN}@github.com/luckzp/luckzp.github.io.git~" _config.yml


script:
  - hexo g
  - hexo d

# E: Build LifeCycle